# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Soft BART matrix transformation
#'
#' @param X_stand A matrix.
#' @param anc A tree matrix.
#' @param tau A double.
#' @export
phi_app <- function(X_stand, anc, tau) {
    .Call('_softmatrix_phi_app', PACKAGE = 'softmatrix', X_stand, anc, tau)
}

